-- =========================================================
-- VELORA — SUPABASE ONLY
-- Cole este arquivo no SQL Editor do Supabase.
--
-- Esta versão usa SOMENTE recursos do Supabase:
--   • Supabase Auth para cadastro/login/sessão
--   • Supabase Database para catálogo e vendas
--   • Supabase Storage para foto de perfil
--   • RPC create_sale para registrar a venda com preço validado
--
-- ATENÇÃO: o bloco RESET abaixo remove as tabelas antigas da VELORA.
-- Ele NÃO apaga usuários existentes do Supabase Auth.
-- =========================================================

create extension if not exists pgcrypto;

-- ---------- RESET DA ESTRUTURA ANTIGA ----------
drop function if exists public.create_sale(jsonb);
drop table if exists public.sale_items cascade;
drop table if exists public.sales cascade;
drop table if exists public.customers cascade;
drop table if exists public.profiles cascade;
drop table if exists public.products cascade;

-- ---------- utilitário updated_at ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------- perfis vinculados ao Supabase Auth ----------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) >= 2),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

-- Cria o perfil automaticamente ao cadastrar um usuário no Supabase Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'name'), ''),
      split_part(coalesce(new.email, 'Cliente'), '@', 1)
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Garante perfil para usuários já existentes no Auth.
insert into public.profiles (id, name)
select
  id,
  coalesce(
    nullif(trim(raw_user_meta_data ->> 'name'), ''),
    split_part(coalesce(email, 'Cliente'), '@', 1)
  )
from auth.users
on conflict (id) do nothing;

-- ---------- produtos ----------
create table public.products (
  id text primary key,
  name text not null,
  category text not null,
  price numeric(10,2) not null check (price >= 0),
  old_price numeric(10,2) check (old_price is null or old_price >= 0),
  badge text,
  image text not null,
  colors jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  description text not null default '',
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index products_category_idx on public.products(category);
create index products_active_sort_idx on public.products(active, sort_order);

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

-- ---------- vendas ----------
create table public.sales (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references auth.users(id) on delete restrict,
  status text not null default 'confirmado',
  subtotal numeric(10,2) not null check (subtotal >= 0),
  shipping_cost numeric(10,2) not null default 0 check (shipping_cost >= 0),
  total numeric(10,2) not null check (total >= 0),
  payment_method text not null default 'fake_card',
  payment_status text not null default 'approved',
  payment_reference text,
  created_at timestamptz not null default now()
);

create index sales_customer_created_idx
  on public.sales(customer_id, created_at desc);

-- ---------- itens da venda ----------
create table public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id uuid not null references public.sales(id) on delete cascade,
  product_id text not null references public.products(id) on delete restrict,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  size text,
  color text,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  subtotal numeric(10,2) not null check (subtotal >= 0)
);

create index sale_items_sale_idx on public.sale_items(sale_id);

-- ---------- RLS ----------
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;

create policy "perfil: ler o próprio"
on public.profiles for select
to authenticated
using (auth.uid() = id);

create policy "perfil: atualizar o próprio"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "produtos: leitura pública"
on public.products for select
to anon, authenticated
using (active = true);

create policy "vendas: cliente lê as próprias"
on public.sales for select
to authenticated
using (auth.uid() = customer_id);

create policy "itens: cliente lê itens das próprias vendas"
on public.sale_items for select
to authenticated
using (
  exists (
    select 1
    from public.sales s
    where s.id = sale_items.sale_id
      and s.customer_id = auth.uid()
  )
);

-- ---------- RPC segura para criar venda ----------
-- A função recebe somente ids/quantidades/opções. O preço vem da tabela
-- products, então o navegador não escolhe o valor final da venda.
create or replace function public.create_sale(p_items jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_sale_id uuid := gen_random_uuid();
  v_subtotal numeric(10,2) := 0;
  v_shipping numeric(10,2) := 0;
  v_total numeric(10,2) := 0;
  v_reference text := 'FAKE-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_line_total numeric(10,2);
begin
  if v_user_id is null then
    raise exception 'Faça login antes de finalizar a compra.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'A venda precisa ter pelo menos um item.';
  end if;

  -- Primeiro valida todos os produtos e calcula o total.
  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(coalesce((v_item ->> 'quantity')::integer, 1), 1);

    select * into v_product
    from public.products
    where id = v_item ->> 'productId'
      and active = true
    for update;

    if not found then
      raise exception 'Produto % não encontrado.', v_item ->> 'productId';
    end if;

    if v_product.stock < v_quantity then
      raise exception 'Estoque insuficiente para %.', v_product.name;
    end if;

    v_subtotal := v_subtotal + (v_product.price * v_quantity);
  end loop;

  -- Frete demonstrativo: grátis a partir de R$ 250, senão R$ 19,90.
  v_shipping := case when v_subtotal >= 250 then 0 else 19.90 end;
  v_total := v_subtotal + v_shipping;

  insert into public.sales (
    id, customer_id, status, subtotal, shipping_cost, total,
    payment_method, payment_status, payment_reference
  ) values (
    v_sale_id, v_user_id, 'confirmado', v_subtotal, v_shipping, v_total,
    'fake_card', 'approved', v_reference
  );

  -- Insere os itens e baixa o estoque.
  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(coalesce((v_item ->> 'quantity')::integer, 1), 1);

    select * into v_product
    from public.products
    where id = v_item ->> 'productId'
    for update;

    v_line_total := v_product.price * v_quantity;

    insert into public.sale_items (
      sale_id, product_id, product_name, quantity, size, color,
      unit_price, subtotal
    ) values (
      v_sale_id,
      v_product.id,
      v_product.name,
      v_quantity,
      nullif(v_item ->> 'size', ''),
      nullif(v_item ->> 'color', ''),
      v_product.price,
      v_line_total
    );

    update public.products
    set stock = stock - v_quantity
    where id = v_product.id;
  end loop;

  return jsonb_build_object(
    'id', v_sale_id,
    'status', 'confirmado',
    'subtotal', v_subtotal,
    'shippingCost', v_shipping,
    'total', v_total,
    'createdAt', now(),
    'payment', jsonb_build_object(
      'method', 'fake_card',
      'status', 'approved',
      'reference', v_reference
    )
  );
end;
$$;

revoke all on function public.create_sale(jsonb) from public;
grant execute on function public.create_sale(jsonb) to authenticated;

-- ---------- Storage: fotos de perfil ----------
drop policy if exists "avatars: leitura pública" on storage.objects;
drop policy if exists "avatars: usuário envia para a própria pasta" on storage.objects;
drop policy if exists "avatars: usuário atualiza a própria pasta" on storage.objects;
drop policy if exists "avatars: usuário apaga da própria pasta" on storage.objects;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "avatars: leitura pública"
on storage.objects for select
to public
using (bucket_id = 'avatars');

create policy "avatars: usuário envia para a própria pasta"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "avatars: usuário atualiza a própria pasta"
on storage.objects for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "avatars: usuário apaga da própria pasta"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- ---------- catálogo demonstrativo ----------
insert into public.products
  (id, name, category, price, old_price, badge, image, colors, sizes, description, stock, active, sort_order)
values
  ('jacket-pulse','Jacket Pulse','Jaquetas',279.90,329.90,'DESTAQUE','jacket-pulse','["#111318","#68517f"]','["P","M","G","GG"]','Casaco estruturado com zíper frontal, bolsos utilitários e faixas violetas cruzadas na cintura.',12,true,1),
  ('blazer-nox','Blazer Nox','Jaquetas',289.90,null,'NOVO','blazer-nox','["#25262a","#8f79a8"]','["P","M","G"]','Blazer preto de modelagem ampla com forro lavanda e acabamento minimalista.',8,true,2),
  ('tailored-axis','Tailored Axis','Calças',219.90,null,null,'tailored-axis','["#24252a","#5f6067"]','["36","38","40","42","44"]','Calça de alfaiataria preta com cintura alta, pregas frontais e perna ampla.',15,true,3),
  ('hoodie-aura','Hoodie Aura','Moletons',189.90,219.90,'-14%','hoodie-aura','["#c8b9db","#eee9f4"]','["P","M","G"]','Moletom cropped lilás, mangas amplas e toque macio para composições urbanas leves.',10,true,4),
  ('knit-ivory','Knit Ivory','Tricôs',149.90,null,'BEST SELLER','knit-ivory','["#eee9df","#d6cfc3"]','["P","M","G"]','Blusa canelada marfim de gola alta com acabamento delicado e linhas anatômicas.',18,true,5),
  ('satin-drift','Satin Drift','Saias',169.90,null,null,'satin-drift','["#151519","#3e3448"]','["P","M","G","GG"]','Saia midi preta acetinada, fluida e assimétrica para looks diurnos ou noturnos.',9,true,6),
  ('sneaker-flux','Sneaker Flux','Calçados',249.90,299.90,'-17%','sneaker-flux','["#f5f3ef","#b8a0d0"]','["37","38","39","40","41","42"]','Tênis branco de sola robusta com pequenos detalhes lilás e visual clean.',14,true,7),
  ('bag-loop','Bag Loop','Acessórios',139.90,null,null,'bag-loop','["#16171b","#68517f"]','["Único"]','Bolsa transversal preta com detalhes violetas, ferragens metálicas e alça regulável.',20,true,8);

-- ---------- verificação ----------
select 'profiles' as recurso, count(*) as registros from public.profiles
union all
select 'products', count(*) from public.products
union all
select 'sales', count(*) from public.sales
union all
select 'sale_items', count(*) from public.sale_items;

-- =========================================================
-- EVOLUÇÃO: API REST + endereço + carrinho + perfil admin
-- =========================================================

-- VELORA — evolução para arquitetura Front-end -> API REST -> Supabase
-- Execute este arquivo se o velora.sql antigo já foi executado no projeto.

-- Dados complementares do cliente
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists zip_code text;
alter table public.profiles add column if not exists street text;
alter table public.profiles add column if not exists number text;
alter table public.profiles add column if not exists complement text;
alter table public.profiles add column if not exists neighborhood text;
alter table public.profiles add column if not exists city text;
alter table public.profiles add column if not exists state text;
alter table public.profiles add column if not exists role text not null default 'customer';

-- Um usuário autenticado pode alterar os próprios dados, mas não pode se promover a admin.
revoke update on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant update (name, avatar_url, phone, zip_code, street, number, complement, neighborhood, city, state)
on public.profiles to authenticated;

-- Carrinho persistido no Supabase para os endpoints /api/cart.
create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  size text,
  color text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, product_id)
);

alter table public.cart_items enable row level security;

drop trigger if exists cart_items_set_updated_at on public.cart_items;
create trigger cart_items_set_updated_at
before update on public.cart_items
for each row execute function public.set_updated_at();

drop policy if exists "carrinho: cliente lê o próprio" on public.cart_items;
drop policy if exists "carrinho: cliente adiciona no próprio" on public.cart_items;
drop policy if exists "carrinho: cliente atualiza o próprio" on public.cart_items;
drop policy if exists "carrinho: cliente remove do próprio" on public.cart_items;

create policy "carrinho: cliente lê o próprio"
on public.cart_items for select to authenticated
using (auth.uid() = customer_id);

create policy "carrinho: cliente adiciona no próprio"
on public.cart_items for insert to authenticated
with check (auth.uid() = customer_id);

create policy "carrinho: cliente atualiza o próprio"
on public.cart_items for update to authenticated
using (auth.uid() = customer_id)
with check (auth.uid() = customer_id);

create policy "carrinho: cliente remove do próprio"
on public.cart_items for delete to authenticated
using (auth.uid() = customer_id);

grant select, insert, update, delete on public.cart_items to authenticated;

-- Permissões administrativas do catálogo. O role só pode ser definido por SQL/dashboard.
drop policy if exists "produtos: admin cadastra" on public.products;
drop policy if exists "produtos: admin atualiza" on public.products;
drop policy if exists "produtos: admin remove" on public.products;

create policy "produtos: admin cadastra"
on public.products for insert to authenticated
with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "produtos: admin atualiza"
on public.products for update to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
)
with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

create policy "produtos: admin remove"
on public.products for delete to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;

-- CEP usado no pedido.
alter table public.sales add column if not exists shipping_cep text;

-- Substitui a função antiga pela versão usada pela API REST.
drop function if exists public.create_sale(jsonb);
drop function if exists public.create_sale(jsonb, text, text);

create function public.create_sale(
  p_items jsonb,
  p_cep text default null,
  p_payment_method text default 'fake_card'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_sale_id uuid := gen_random_uuid();
  v_subtotal numeric(10,2) := 0;
  v_shipping numeric(10,2) := 0;
  v_total numeric(10,2) := 0;
  v_reference text := 'FAKE-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_line_total numeric(10,2);
  v_cep text := nullif(regexp_replace(coalesce(p_cep, ''), '[^0-9]', '', 'g'), '');
  v_first_digit integer;
  v_payment_method text := case when p_payment_method in ('fake_card', 'fake_pix') then p_payment_method else 'fake_card' end;
begin
  if v_user_id is null then
    raise exception 'Faça login antes de finalizar a compra.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'A venda precisa ter pelo menos um item.';
  end if;

  if v_cep is not null and char_length(v_cep) <> 8 then
    raise exception 'CEP inválido. Informe 8 dígitos.';
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(coalesce((v_item ->> 'quantity')::integer, 1), 1);

    select * into v_product
    from public.products
    where id = v_item ->> 'productId'
      and active = true
    for update;

    if not found then
      raise exception 'Produto % não encontrado.', v_item ->> 'productId';
    end if;

    if v_product.stock < v_quantity then
      raise exception 'Estoque insuficiente para %.', v_product.name;
    end if;

    v_subtotal := v_subtotal + (v_product.price * v_quantity);
  end loop;

  if v_subtotal >= 299 then
    v_shipping := 0;
  elsif v_cep is null then
    v_shipping := 19.90;
  else
    v_first_digit := substr(v_cep, 1, 1)::integer;
    if v_first_digit <= 3 then
      v_shipping := 14.90;
    elsif v_first_digit <= 6 then
      v_shipping := 19.90;
    else
      v_shipping := 24.90;
    end if;
  end if;

  v_total := v_subtotal + v_shipping;

  insert into public.sales (
    id, customer_id, status, subtotal, shipping_cost, shipping_cep, total,
    payment_method, payment_status, payment_reference
  ) values (
    v_sale_id, v_user_id, 'confirmado', v_subtotal, v_shipping, v_cep, v_total,
    v_payment_method, 'approved', v_reference
  );

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(coalesce((v_item ->> 'quantity')::integer, 1), 1);

    select * into v_product
    from public.products
    where id = v_item ->> 'productId'
    for update;

    v_line_total := v_product.price * v_quantity;

    insert into public.sale_items (
      sale_id, product_id, product_name, quantity, size, color, unit_price, subtotal
    ) values (
      v_sale_id,
      v_product.id,
      v_product.name,
      v_quantity,
      nullif(v_item ->> 'size', ''),
      nullif(v_item ->> 'color', ''),
      v_product.price,
      v_line_total
    );

    update public.products
    set stock = stock - v_quantity
    where id = v_product.id;
  end loop;

  return jsonb_build_object(
    'id', v_sale_id,
    'status', 'confirmado',
    'subtotal', v_subtotal,
    'shippingCost', v_shipping,
    'shippingCep', v_cep,
    'total', v_total,
    'createdAt', now(),
    'payment', jsonb_build_object(
      'method', v_payment_method,
      'status', 'approved',
      'reference', v_reference
    )
  );
end;
$$;

revoke all on function public.create_sale(jsonb, text, text) from public;
grant execute on function public.create_sale(jsonb, text, text) to authenticated;

-- Para transformar uma conta em administrador, rode manualmente trocando o e-mail:
-- update public.profiles
-- set role = 'admin'
-- where id = (select id from auth.users where email = 'admin@velora.com');

